### ISSUE TITLE
环境变量

### ISSUE THREAD

**Issue by wang1kun** [canhetingsky/aliyunpan_sign#2]
大佬们，能否教一下windows的环境变量怎么弄，一直不会，报错

**Comment by canhetingsky** [comment]
> 抱歉，有点晚了，但还是回复下。`

1. 简单点直接改下程序，获取环境变量那里写上自己的数据。

![](https://media.canheting.cn/img/202302191544445.png)

2. Windows添加环境变量可以参考下图：

![Windows添加用户环境变量](https://media.canheting.cn//img/202305172329747.png)
